### ISSUE TITLE
Define Models

### ISSUE THREAD

**Issue by mattmcmanus** [schoolsOut/schoolsOut#1]
# "Models"/collections
* Category - (Online Learning, Virtual Tour, Podcast, etc)
* Subject - (eg, Art, History, STEM, etc)
  * Description
* Resource
  * Relation to category
  * Relation Subject
  * Name
  * URL
  * Description
  * Checkbox for the various education levels

The live classes are a little more interesting. We could add the appropriate fields (day, time) for resource, but that may be too much and it might be best as a separate model. I could go either way. The deciding factor would be how the folks who will be maintaining the airtable think about them and what would be most effective for them

**Comment by mminkoff** [comment]
I've already spoken with her about the live classes.  She's going to create google calendars for each category, and ideally we'll find a widget that displays them all, with the ability to select a subset.

Otherwise, all the resources should be the same.  The only other concern is that the videos need to say which streaming service carries them.
